<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "forum"
 *
 * Auto generated by Extension Builder 2013-07-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Forum',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Bastian Bringenberg, Michael Ecker, Florian Dehn',
	'author_email' => 'bastian.bringenberg@typo3.org, m.ecker@stadeleck.de, flo@katzefudder.de',
	'author_company' => 'BBNetz.eu, Stadeleck, katzefudder.de',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.5',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>